# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: A Blog on Data Analytics
email: kazmialiarsalan@gmail.com
description: Ali Arsalan Kazmi
baseurl: "/blog_DA" # the subpath of your site, e.g. /blog
url: "http://aliarsalankazmi.github.io/blog_DA" # the base hostname & protocol for your site
twitter_username: scac1041
github_username:  aliarsalankazmi

# Build settings
markdown: kramdown
